/**
 * Parity test: the JS StreamingSegmenter must produce byte-identical hold
 * frames to sofi_streaming.py on real PSL-CFRT keypoint sequences.
 *
 * A browser port that silently diverges from the validated Python version
 * would make the live demo untrustworthy and the divergence very hard to
 * notice by eye, so this is checked rather than assumed.
 *
 * Usage:  node web/test_parity.mjs <fixture.json>
 * The fixture is generated by the "export JS parity fixture" cell in
 * streaming_segmentation.ipynb.
 */
import { readFileSync } from "node:fs";
import { StreamingSegmenter } from "./sofi_streaming.js";

const path = process.argv[2];
if (!path) {
  console.error("usage: node web/test_parity.mjs <fixture.json>");
  process.exit(2);
}

const cases = JSON.parse(readFileSync(path, "utf8"));
let pass = 0, fail = 0, totalFrames = 0;
const failures = [];

for (const c of cases) {
  const seg = new StreamingSegmenter({ fps: c.fps });

  // configuration must match Python's before we even look at the output
  const cfg = c.config;
  if (seg.smoothWin !== cfg.smooth || seg.run !== cfg.run ||
      seg.minSep !== cfg.min_sep || seg.delay !== cfg.delay) {
    failures.push(`${c.signer}/${c.video}@${c.fps}: config mismatch ` +
      `js={smooth:${seg.smoothWin},run:${seg.run},minSep:${seg.minSep},delay:${seg.delay}} ` +
      `py=${JSON.stringify(cfg)}`);
    fail++;
    continue;
  }

  const got = [];
  for (const f of c.frames) {
    const events = f === null ? seg.push(null, null) : seg.push(f[0], f[1]);
    for (const h of events) got.push(h.frame);
  }
  for (const h of seg.finish()) got.push(h.frame);
  totalFrames += c.frames.length;

  const want = c.expected;
  const same = got.length === want.length && got.every((v, i) => v === want[i]);
  if (same) {
    pass++;
  } else {
    fail++;
    if (failures.length < 6) {
      failures.push(`${c.signer}/${c.video}@${c.fps}fps\n    js: [${got}]\n    py: [${want}]`);
    }
  }
}

console.log(`fixture cases : ${cases.length}`);
console.log(`frames replayed: ${totalFrames}`);
console.log(`exact match    : ${pass}`);
console.log(`mismatch       : ${fail}`);
if (failures.length) {
  console.log("\nfailures:");
  for (const f of failures) console.log("  " + f);
}
process.exit(fail === 0 ? 0 : 1);
